const String supabaseUrl = 'https://apxratpxjerroelmkclb.supabase.co';
const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFweHJhdHB4amVycm9lbG1rY2xiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgwNDMxMzMsImV4cCI6MjA5MzYxOTEzM30.1Dy93gj4KAV2tEYhVQR4VYPocf5Ej4MeukTLn0BIP-U';
